### ISSUE TITLE
NumField of non-struct type

### ISSUE THREAD

**Issue by guatedude2** [jinzhu/copier#10]
Not sure if interface{} objects are supported but I'm trying to clone a JSON object of type `map[string]interface{}` without success.

Here's my test:

```
import "mytest/copier"
import "encoding/json"
import "io/ioutil"
import "fmt"

func main() {
    var jsonObject map[string]interface{}
    data, _ := ioutil.ReadFile("./test.json")
    json.NewDecoder(data).Decode(&jsonObject)
    fmt.Println("Result:", jsonObject)
}
```

Output:

```
panic: reflect: NumField of non-struct type

goroutine 1 [running]:
panic(0x361fc0, 0xc42013abe0)
        /usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
reflect.(*rtype).NumField(0x396420, 0xabdc8)
        /usr/local/Cellar/go/1.7.3/libexec/src/reflect/type.go:1003 +0x96
copier.deepFields(0x58fac0, 0x396420, 0x195, 0x58fac0, 0x396420)
        /Users/guatedude/Projects/go/src/mytest/copier/copier.go:123 +0x76
copier.Copy(0x384820, 0xc420134230, 0x384820, 0xc420134228, 0xc420131470, 0xc42012d640)
        /Users/guatedude/Projects/go/src/mytest/copier/copier.go:70 +0x3d2
main.main()
        /Users/guatedude/Projects/go/src/mytest/main.go:63 +0x11c7
```

**Comment by kchugalinskiy** [comment]
@guatedude2 the answer is a bit simplier - interface{} are supported, but map's aren't :-) You are free to contribute ;-)

**Comment by jinzhu** [comment]
Hi @guatedude2 

Yes, map is not supported.
